# お約束の設定

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 乱数の生成

In [2]:
from numpy.random import *

rand()      # 0〜1の乱数を1個生成
rand(100)   # 0〜1の乱数を100個生成
rand(10,10) # 0〜1の乱数で 10x10 の行列を生成

rand(100) * 40 + 30 # 30〜70の乱数を100個生成

array([40.83070491, 54.1500143 , 49.19062348, 67.93343242, 55.74131277,
       47.37134057, 44.86557409, 47.09230769, 68.54907832, 60.57965048,
       68.48638394, 47.28741584, 46.45504356, 34.12363942, 51.10311778,
       38.85983687, 59.46023191, 66.89851937, 57.69690838, 59.22442859,
       66.19148807, 37.47242696, 69.7783993 , 69.75419917, 39.08214164,
       42.99885271, 60.95753959, 40.29445133, 42.95956657, 44.69802711,
       38.59529903, 55.53208804, 53.26244786, 66.38433947, 44.88237639,
       61.67561111, 33.33361408, 47.20397122, 68.38178876, 61.5274469 ,
       56.31002454, 43.81683775, 55.53099251, 56.9059643 , 32.66094701,
       65.24274741, 63.72838561, 51.85650892, 31.44760869, 66.10387254,
       33.53278596, 59.27122489, 53.79532256, 47.6010565 , 49.23405672,
       69.8689789 , 66.57952661, 40.37662689, 53.0017214 , 32.44244177,
       62.24755201, 36.60877983, 32.89429537, 37.02931509, 45.5402673 ,
       36.17228405, 54.18517243, 66.97269851, 36.54811203, 62.10

# 配列の練習

### パック/アンパック

In [4]:
#アンパック
x = np.array([[11,12],[21,22]])
print(x)

print(*x.shape)

[[11 12]
 [21 22]]
2 2


In [10]:
#アンパックを使ったランダム値の要素を持つ行列の生成
y = np.random.rand(*x.shape)
print(y)

dropout_ratio = 0.5
mask = y > dropout_ratio #dropout_ratio以上のものを得る。
print(mask)

#数値にTrueを掛けるとそのままに、Falseを掛けると0になる性質がある。
print(5*True)
print(10*False)

#maskを掛けると、dropout_ratio以上の要素のみが残ることになる。
print(y * mask)

[[0.6459997  0.96034386]
 [0.7483538  0.44606977]]
[[ True  True]
 [ True False]]
5
0
[[0.6459997  0.96034386]
 [0.7483538  0.        ]]


# 参考URL
1. 乱数の生成
https://qiita.com/yubais/items/bf9ce0a8fefdcc0b0c97
    
2. パック/アンパック
https://docs.python.org/ja/3.7/tutorial/controlflow.html#unpacking-argument-lists