# お約束の設定

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 乱数の生成

In [2]:
from numpy.random import *

rand()      # 0〜1の乱数を1個生成
rand(100)   # 0〜1の乱数を100個生成
rand(10,10) # 0〜1の乱数で 10x10 の行列を生成

rand(100) * 40 + 30 # 30〜70の乱数を100個生成

array([48.52523637, 60.57060898, 69.14201634, 65.42239085, 60.96711142,
       44.22894311, 31.52709557, 40.64494946, 58.39729264, 38.6801577 ,
       63.4761644 , 50.49751718, 53.24870856, 45.65335628, 35.0210837 ,
       58.55208043, 43.58707238, 35.9097444 , 47.82958991, 67.3984736 ,
       63.4829392 , 57.84190334, 65.80874604, 61.7822718 , 39.99902499,
       46.56499387, 34.75636759, 59.67780727, 46.0057947 , 46.09500445,
       37.22605543, 69.92225512, 61.12412256, 51.09972197, 37.1845757 ,
       69.10806062, 43.56354391, 67.12167633, 69.77075916, 35.87718946,
       46.84209464, 53.78398851, 50.40496122, 52.44288953, 58.09488335,
       53.43576021, 65.24907282, 58.76697947, 55.34900818, 54.94553802,
       60.32930066, 57.32243988, 64.79222462, 49.11004456, 47.6605458 ,
       38.70081406, 36.95271052, 59.90189741, 54.28951295, 64.05128094,
       32.36035689, 53.83237068, 54.295761  , 46.32738956, 50.01702305,
       49.60367578, 47.00809925, 63.9452177 , 32.73897816, 39.21

In [3]:
#numpy.random.uniformは、任意の範囲の連続一様分布から浮動小数点数の乱数を生成する関数です。
#https://www.headboost.jp/numpy-random-uniform/
print(np.random.uniform(-8, -4))

-5.502026008880998


# 配列の練習

### パック/アンパック

In [4]:
#アンパック
x = np.array([[11,12],[21,22]])
print(x)

print(*x.shape)

[[11 12]
 [21 22]]
2 2


In [5]:
#アンパックを使ったランダム値の要素を持つ行列の生成
y = np.random.rand(*x.shape)
print(y)

dropout_ratio = 0.5
mask = y > dropout_ratio #dropout_ratio以上のものを得る。
print(mask)

#数値にTrueを掛けるとそのままに、Falseを掛けると0になる性質がある。
print(5*True)
print(10*False)

#maskを掛けると、dropout_ratio以上の要素のみが残ることになる。
print(y * mask)

[[0.89075655 0.91505058]
 [0.03860913 0.2336657 ]]
[[ True  True]
 [False False]]
5
0
[[0.89075655 0.91505058]
 [0.         0.        ]]


### データのシャッフルと順列

#### shuffle_dataset関数で使っているnumpyのテクニック

In [6]:
#https://www.headboost.jp/numpy-random-permutation/
#numpy.random.permutationは、渡した配列の要素をランダムに並べ替える関数です。多次元配列を渡した場合は最初の軸だけを並べ替えます。
x = np.array([[11,12],[21,22]])
print(x)
#[[11 12]
#[21 22]]

print(x.shape[0])
#[0 1]
print(np.random.permutation(x.shape[0]))
#ランダムに並べ替えるので、以下のようになる場合がある
#[1 0]

print(np.random.permutation(x))
#ランダムに並べ替えるので、以下のようになる場合がある
#[[21 22]
# [11 12]]

#次元数が2の場合
print("次元数が2の場合")
permutation = np.random.permutation(x.shape[0])
print("permutation=%s" % (permutation))
print(x[permutation,:] ) #以下のようになる場合がある
#permutation=[1 0]
#array([[21, 22],
#       [11, 12]])

#以下はnumpy配列へのアクセス方法について
#スライスを使っている。スライスについては、以下のＵＲＬが良くわかる
#https://www.headboost.jp/python-numpy-array-how-to-handle/
print("以下はnumpy配列へのアクセス方法について")
print(x[1])
print(x[:]) #すべての要素
print(x[:,1]) #2列目　→　[12 22]　※２列目が抜き出されて１次元配列になってくる。
print(x[1,:]) #2行目　→　[21, 22]
print(x[0,:]) #1行目　→　[11, 12]

print("こんなふうにアクセスの仕方を配列で指定できる")
print(x[[1,0],:])

[[11 12]
 [21 22]]
2
[0 1]
[[21 22]
 [11 12]]
次元数が2の場合
permutation=[1 0]
[[21 22]
 [11 12]]
以下はnumpy配列へのアクセス方法について
[21 22]
[[11 12]
 [21 22]]
[12 22]
[21 22]
[11 12]
こんなふうにアクセスの仕方を配列で指定できる
[[21 22]
 [11 12]]


ここまでわかったので、shuffle_datasetについて理解した。コメントを入れておく。

In [7]:
def shuffle_dataset(x, t):
    """データセットのシャッフルを行う

    Parameters
    ----------
    x : 訓練データ
    t : 教師データ

    Returns
    -------
    x, t : シャッフルを行った訓練データと教師データ
    """
    permutation = np.random.permutation(x.shape[0]) #入力データの最初の次元について配列化する。例えば、2*2行列ならx.shape[0]は[0, 1]
    x = x[permutation,:] if x.ndim == 2 else x[permutation,:,:,:] #2次元配列であれば、行だけを並び替えて、後の列はそのまま。２次元を超える配列場合、例えば、畳み込み演算で使う４次元配列の場合も同じ考え方で並び替え
    t = t[permutation] #正解ラベルは１次元なので、permutationで並び替えるだけ。

    return x, t

### reshape

# 参考URL
1. 乱数の生成
https://qiita.com/yubais/items/bf9ce0a8fefdcc0b0c97
    
2. パック/アンパック
https://docs.python.org/ja/3.7/tutorial/controlflow.html#unpacking-argument-lists

3. 配列のスライスについて
https://www.headboost.jp/python-numpy-array-how-to-handle/