# お約束の設定

In [1]:
# coding: utf-8
import numpy as np
import matplotlib.pyplot as plt
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定

from my_common.util import init_sample_matrix

# 乱数の生成

In [2]:
from numpy.random import *

rand()      # 0〜1の乱数を1個生成
rand(100)   # 0〜1の乱数を100個生成
rand(10,10) # 0〜1の乱数で 10x10 の行列を生成

rand(100) * 40 + 30 # 30〜70の乱数を100個生成

array([59.45452824, 66.67601328, 37.72320743, 40.09451764, 66.70529841,
       47.42383462, 36.29880586, 46.1773335 , 53.54638425, 52.61687128,
       31.83570381, 35.62870602, 34.39764064, 59.83991914, 46.5944544 ,
       45.39451394, 31.21061801, 58.37618177, 33.52870485, 64.70776279,
       55.53843378, 57.17547862, 52.22809148, 34.52820409, 42.41058977,
       40.74512039, 30.75484352, 51.64836246, 43.48179621, 40.53392988,
       36.55242555, 51.34770136, 40.76485686, 39.22901701, 41.36004196,
       37.84435857, 50.64648384, 55.50016019, 59.41702098, 47.94850058,
       62.33230724, 30.52723642, 51.55318508, 68.52481394, 50.12784604,
       39.12055819, 37.56073823, 49.02391972, 51.70323948, 56.46064657,
       58.51818766, 67.76379752, 57.2395879 , 48.41106645, 46.06738571,
       40.24262028, 38.53515324, 68.29715476, 39.03049561, 30.48613037,
       39.75600475, 48.89694284, 45.84016284, 64.681633  , 36.8017029 ,
       31.35782352, 52.7822134 , 32.64202191, 31.68064777, 36.36

In [3]:
#numpy.random.uniformは、任意の範囲の連続一様分布から浮動小数点数の乱数を生成する関数です。
#https://www.headboost.jp/numpy-random-uniform/
print(np.random.uniform(-8, -4))

-7.921018511397967


# 配列の練習

### 要素アクセス

In [4]:
print("データの準備")

#入力画像の高さ、幅、および、チャネル数。画像の枚数
H  = 4
W  = 5
C  = 1 #mnistはチャンネル数1のようなので、このサンプルテストもそれに合わせる(7.4.2と同じ)
N  = 2 #入力画像の枚数

#poolingレイヤの基本パラメータ
pool_h = 2
pool_w = 2
stride = 2
pad    = 0

#出力データ（画像）の高さと幅（自動的に計算される。）
out_h = int(1 + (H - pool_h) / stride)
out_w = int(1 + (W - pool_w) / stride)

print("出力画像の高さ=%d と 幅=%d" % (out_h ,out_w))

#xの用意(mnistはチャンネル数1のようなので、このテストもそれに合わせる)
print("=== preparing of x===")
x1 = init_sample_matrix(filter_num = 1, channel=C, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)
x2 = init_sample_matrix(filter_num = 2, channel=C, height=H, width=W)
x = np.array([[x1],[x2]])
print(x.shape)
print(x)

データの準備
出力画像の高さ=2 と 幅=2
=== preparing of x===
(2, 1, 4, 5)
[[[[1111 1112 1113 1114 1115]
   [1121 1122 1123 1124 1125]
   [1131 1132 1133 1134 1135]
   [1141 1142 1143 1144 1145]]]


 [[[2111 2112 2113 2114 2115]
   [2121 2122 2123 2124 2125]
   [2131 2132 2133 2134 2135]
   [2141 2142 2143 2144 2145]]]]


In [5]:
print("データアクセスの練習")
print(x)
print(x.shape)
print("すべての１次元と２次元目において、３次元目と４次元目が(0,0)の座標のものを取り出す。要するに、すべての画像とチャネルに対して座標が(0,0)のものを取り出す")
print(x[:,:,0,0])
print(x[:,:,0,0].shape)

print("範囲指定(start:endで、endは範囲に含まない)")
print(x[:,:,0:1,0:1])
print(x[:,:,0:1,0:1].shape)

print("範囲指定")
print(x[:,:,0:2,0:2])
print(x[:,:,0:2,0:2].shape)

print("範囲指定")
print(x[:,:,0:2:1,0:2:1])
print(x[:,:,0:2:1,0:2:1].shape)

print("範囲指定")
print(x[:,:,0:4:2,0:4:2])
print(x[:,:,0:4:2,0:4:2].shape)


a_1d = np.arange(10)
print(a_1d)
# [0 1 2 3 4 5 6 7 8 9]

print(a_1d[2:7])
# [2 3 4 5 6]

print(a_1d[:7])
# [0 1 2 3 4 5 6]

print(a_1d[2:])
# [2 3 4 5 6 7 8 9]

print(a_1d[2:7:2])
# [2 4 6] #1つとばし

print(a_1d[2:7:1])
# [2 3 4 5 6] #0つとばし、つまり飛ばさない。



データアクセスの練習
[[[[1111 1112 1113 1114 1115]
   [1121 1122 1123 1124 1125]
   [1131 1132 1133 1134 1135]
   [1141 1142 1143 1144 1145]]]


 [[[2111 2112 2113 2114 2115]
   [2121 2122 2123 2124 2125]
   [2131 2132 2133 2134 2135]
   [2141 2142 2143 2144 2145]]]]
(2, 1, 4, 5)
すべての１次元と２次元目において、３次元目と４次元目が(0,0)の座標のものを取り出す。要するに、すべての画像とチャネルに対して座標が(0,0)のものを取り出す
[[1111]
 [2111]]
(2, 1)
範囲指定(start:endで、endは範囲に含まない)
[[[[1111]]]


 [[[2111]]]]
(2, 1, 1, 1)
範囲指定
[[[[1111 1112]
   [1121 1122]]]


 [[[2111 2112]
   [2121 2122]]]]
(2, 1, 2, 2)
範囲指定
[[[[1111 1112]
   [1121 1122]]]


 [[[2111 2112]
   [2121 2122]]]]
(2, 1, 2, 2)
範囲指定
[[[[1111 1113]
   [1131 1133]]]


 [[[2111 2113]
   [2131 2133]]]]
(2, 1, 2, 2)
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[0 1 2 3 4 5 6]
[2 3 4 5 6 7 8 9]
[2 4 6]
[2 3 4 5 6]


### パック/アンパック

In [6]:
#アンパック
x = np.array([[11,12],[21,22]])
print(x)

print(*x.shape)

[[11 12]
 [21 22]]
2 2


In [7]:
#アンパックを使ったランダム値の要素を持つ行列の生成
y = np.random.rand(*x.shape)
print(y)

dropout_ratio = 0.5
mask = y > dropout_ratio #dropout_ratio以上のものを得る。
print(mask)

#数値にTrueを掛けるとそのままに、Falseを掛けると0になる性質がある。
print(5*True)
print(10*False)

#maskを掛けると、dropout_ratio以上の要素のみが残ることになる。
print(y * mask)

[[0.01862232 0.27793109]
 [0.92120845 0.81203712]]
[[False False]
 [ True  True]]
5
0
[[0.         0.        ]
 [0.92120845 0.81203712]]


### データのシャッフルと順列

#### shuffle_dataset関数で使っているnumpyのテクニック

In [8]:
#https://www.headboost.jp/numpy-random-permutation/
#numpy.random.permutationは、渡した配列の要素をランダムに並べ替える関数です。多次元配列を渡した場合は最初の軸だけを並べ替えます。
x = np.array([[11,12],[21,22]])
print(x)
#[[11 12]
#[21 22]]

print(x.shape[0])
#[0 1]
print(np.random.permutation(x.shape[0]))
#ランダムに並べ替えるので、以下のようになる場合がある
#[1 0]

print(np.random.permutation(x))
#ランダムに並べ替えるので、以下のようになる場合がある
#[[21 22]
# [11 12]]

#次元数が2の場合
print("次元数が2の場合")
permutation = np.random.permutation(x.shape[0])
print("permutation=%s" % (permutation))
print(x[permutation,:] ) #以下のようになる場合がある
#permutation=[1 0]
#array([[21, 22],
#       [11, 12]])

#以下はnumpy配列へのアクセス方法について
#スライスを使っている。スライスについては、以下のＵＲＬが良くわかる
#https://www.headboost.jp/python-numpy-array-how-to-handle/
print("以下はnumpy配列へのアクセス方法について")
print(x[1])
print(x[:]) #すべての要素
print(x[:,1]) #2列目　→　[12 22]　※２列目が抜き出されて１次元配列になってくる。
print(x[1,:]) #2行目　→　[21, 22]
print(x[0,:]) #1行目　→　[11, 12]

print("こんなふうにアクセスの仕方を配列で指定できる")
print(x[[1,0],:])

[[11 12]
 [21 22]]
2
[0 1]
[[11 12]
 [21 22]]
次元数が2の場合
permutation=[1 0]
[[21 22]
 [11 12]]
以下はnumpy配列へのアクセス方法について
[21 22]
[[11 12]
 [21 22]]
[12 22]
[21 22]
[11 12]
こんなふうにアクセスの仕方を配列で指定できる
[[21 22]
 [11 12]]


ここまでわかったので、shuffle_datasetについて理解した。コメントを入れておく。

In [9]:
def shuffle_dataset(x, t):
    """データセットのシャッフルを行う

    Parameters
    ----------
    x : 訓練データ
    t : 教師データ

    Returns
    -------
    x, t : シャッフルを行った訓練データと教師データ
    """
    permutation = np.random.permutation(x.shape[0]) #入力データの最初の次元について配列化する。例えば、2*2行列ならx.shape[0]は[0, 1]
    x = x[permutation,:] if x.ndim == 2 else x[permutation,:,:,:] #2次元配列であれば、行だけを並び替えて、後の列はそのまま。２次元を超える配列場合、例えば、畳み込み演算で使う４次元配列の場合も同じ考え方で並び替え
    t = t[permutation] #正解ラベルは１次元なので、permutationで並び替えるだけ。

    return x, t

### reshape

# transpose

In [10]:
from my_common.util import init_sample_matrix

In [11]:
#入力画像の高さ、幅、および、チャネル数。画像の枚数
H  = 2
W  = 2 
C  = 2 
N  = 2 #入力画像の枚数
#xの用意
print("=== preparing of x===")
x1 = init_sample_matrix(filter_num = 0, channel=1, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)
x2 = init_sample_matrix(filter_num = 0, channel=2, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)
x3 = init_sample_matrix(filter_num = 0, channel=3, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)

x = np.array([x1,x2,x3])
print(x.shape)
print(x)

print("x.transpose(2,1,0)")
print("https://deepage.net/features/numpy-transpose.htmlの解説にあるとおり、x(i,j,k)→x'(k,j,i)に変換する処理")
print("直感的には行１つ飛ばしで見つけた要素を、新しい行ベクトルにしている")
print(x.transpose(2,1,0))

=== preparing of x===
(3, 2, 2)
[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
x.transpose(2,1,0)
https://deepage.net/features/numpy-transpose.htmlの解説にあるとおり、x(i,j,k)→x'(k,j,i)に変換する処理
直感的には行１つ飛ばしで見つけた要素を、新しい行ベクトルにしている
[[[111 211 311]
  [121 221 321]]

 [[112 212 312]
  [122 222 322]]]


# np.pad
参考URL[3]が秀逸だったので、あえて説明的な記事はここには記載していない。

In [12]:
import numpy as np


x_1d = np.arange(1, 3 + 1) #startが1、stopが4。arangeはstop未満なので、よって1~3までの数値を生成する。
print(x_1d)

[1 2 3]


In [13]:
print(np.pad(x_1d, ((1, 1))))
print(np.pad(x_1d, ((2, 1))))
print(np.pad(x_1d, ((1, 2))))

[0 1 2 3 0]
[0 0 1 2 3 0]
[0 1 2 3 0 0]


これならなんとなくわかりますよね？1次元ですので指定可能なtupleは1つだけで、before_1で指定している数だけ配列の左に、after_1で指定している数だけ配列の右に、それぞれ00でパディングされていますね。
ちなみに二重タプルで書いているつもりですが、実はPythonでは単タプルと同様の扱いをされています。

In [14]:
print(np.pad(x_1d, ((1, 1),)))
print(np.pad(x_1d, ((2, 1),)))
print(np.pad(x_1d, ((1, 2),)))

[0 1 2 3 0]
[0 0 1 2 3 0]
[0 1 2 3 0 0]


はい、結果は一緒ですね。こちらでは明示的に二重タプルとして引数を送っています。

In [15]:
print(np.pad(x_1d, (1,)))
print(np.pad(x_1d, (2,)))
print(np.pad(x_1d, 1))
print(np.pad(x_1d, 2))

[0 1 2 3 0]
[0 0 1 2 3 0 0]
[0 1 2 3 0]
[0 0 1 2 3 0 0]


両端に指定した数だけ00が埋められていますね。この指定方法だと両端とも同じ数だけパディングされます。

In [16]:
x_2d = np.arange(1, 3*3 + 1).reshape(3, 3)
print(x_2d)

print(np.pad(x_2d, ((1, 1), (2, 2))))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 7 8 9 0 0]
 [0 0 0 0 0 0 0]]


さて、2次元の場合は1次元目である行(上下)にまずパディングされ、その次に2次元目の列(左右)にパディングされています。それ以外は1次元の時と同じですね。

これ以上の詳しい説明は[3]を参照

# 参考URL
1. 乱数の生成
https://qiita.com/yubais/items/bf9ce0a8fefdcc0b0c97
    
2. パック/アンパック
https://docs.python.org/ja/3.7/tutorial/controlflow.html#unpacking-argument-lists

3. 配列のスライスについて
https://www.headboost.jp/python-numpy-array-how-to-handle/

4. np.padについて、詳しく具体例がありわかりやすい(numpy.pad関数完全理解)
https://qiita.com/kuroitu/items/51f4c867c8a44de739ec