# お約束の設定

In [1]:
# coding: utf-8
import numpy as np
import matplotlib.pyplot as plt
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定

# 乱数の生成

In [2]:
from numpy.random import *

rand()      # 0〜1の乱数を1個生成
rand(100)   # 0〜1の乱数を100個生成
rand(10,10) # 0〜1の乱数で 10x10 の行列を生成

rand(100) * 40 + 30 # 30〜70の乱数を100個生成

array([58.60428159, 60.24901169, 45.50763436, 48.38015454, 36.76959582,
       67.86968564, 40.65055564, 41.92995387, 35.42820129, 36.29642875,
       56.90605609, 61.96567585, 50.59132453, 43.67546599, 55.87983585,
       61.71078782, 55.73068746, 67.36976242, 34.76505229, 35.01111412,
       59.44009754, 56.7921052 , 52.65649051, 32.07114549, 34.03763275,
       68.15452018, 47.82761016, 39.15453202, 51.70930514, 48.99848771,
       35.56656272, 64.72539414, 53.03650314, 48.329098  , 36.42652793,
       37.22944461, 60.3367437 , 62.76108157, 63.85244856, 63.35204414,
       46.05538734, 37.1494832 , 36.40247363, 31.87641925, 33.95903656,
       62.65594801, 42.17579192, 41.49339825, 57.11409876, 31.55755494,
       62.49143883, 50.00158929, 69.99151019, 68.12788217, 66.50701888,
       39.39911012, 52.27489137, 68.15684362, 43.27199806, 47.45742202,
       61.58595303, 49.15775716, 31.81396029, 50.17786689, 43.86811672,
       34.07456417, 63.87337822, 59.92218121, 60.93313   , 62.23

In [3]:
#numpy.random.uniformは、任意の範囲の連続一様分布から浮動小数点数の乱数を生成する関数です。
#https://www.headboost.jp/numpy-random-uniform/
print(np.random.uniform(-8, -4))

-4.952923282380889


# 配列の練習

### パック/アンパック

In [4]:
#アンパック
x = np.array([[11,12],[21,22]])
print(x)

print(*x.shape)

[[11 12]
 [21 22]]
2 2


In [5]:
#アンパックを使ったランダム値の要素を持つ行列の生成
y = np.random.rand(*x.shape)
print(y)

dropout_ratio = 0.5
mask = y > dropout_ratio #dropout_ratio以上のものを得る。
print(mask)

#数値にTrueを掛けるとそのままに、Falseを掛けると0になる性質がある。
print(5*True)
print(10*False)

#maskを掛けると、dropout_ratio以上の要素のみが残ることになる。
print(y * mask)

[[0.42459475 0.12598878]
 [0.79339768 0.95141657]]
[[False False]
 [ True  True]]
5
0
[[0.         0.        ]
 [0.79339768 0.95141657]]


### データのシャッフルと順列

#### shuffle_dataset関数で使っているnumpyのテクニック

In [6]:
#https://www.headboost.jp/numpy-random-permutation/
#numpy.random.permutationは、渡した配列の要素をランダムに並べ替える関数です。多次元配列を渡した場合は最初の軸だけを並べ替えます。
x = np.array([[11,12],[21,22]])
print(x)
#[[11 12]
#[21 22]]

print(x.shape[0])
#[0 1]
print(np.random.permutation(x.shape[0]))
#ランダムに並べ替えるので、以下のようになる場合がある
#[1 0]

print(np.random.permutation(x))
#ランダムに並べ替えるので、以下のようになる場合がある
#[[21 22]
# [11 12]]

#次元数が2の場合
print("次元数が2の場合")
permutation = np.random.permutation(x.shape[0])
print("permutation=%s" % (permutation))
print(x[permutation,:] ) #以下のようになる場合がある
#permutation=[1 0]
#array([[21, 22],
#       [11, 12]])

#以下はnumpy配列へのアクセス方法について
#スライスを使っている。スライスについては、以下のＵＲＬが良くわかる
#https://www.headboost.jp/python-numpy-array-how-to-handle/
print("以下はnumpy配列へのアクセス方法について")
print(x[1])
print(x[:]) #すべての要素
print(x[:,1]) #2列目　→　[12 22]　※２列目が抜き出されて１次元配列になってくる。
print(x[1,:]) #2行目　→　[21, 22]
print(x[0,:]) #1行目　→　[11, 12]

print("こんなふうにアクセスの仕方を配列で指定できる")
print(x[[1,0],:])

[[11 12]
 [21 22]]
2
[0 1]
[[21 22]
 [11 12]]
次元数が2の場合
permutation=[1 0]
[[21 22]
 [11 12]]
以下はnumpy配列へのアクセス方法について
[21 22]
[[11 12]
 [21 22]]
[12 22]
[21 22]
[11 12]
こんなふうにアクセスの仕方を配列で指定できる
[[21 22]
 [11 12]]


ここまでわかったので、shuffle_datasetについて理解した。コメントを入れておく。

In [7]:
def shuffle_dataset(x, t):
    """データセットのシャッフルを行う

    Parameters
    ----------
    x : 訓練データ
    t : 教師データ

    Returns
    -------
    x, t : シャッフルを行った訓練データと教師データ
    """
    permutation = np.random.permutation(x.shape[0]) #入力データの最初の次元について配列化する。例えば、2*2行列ならx.shape[0]は[0, 1]
    x = x[permutation,:] if x.ndim == 2 else x[permutation,:,:,:] #2次元配列であれば、行だけを並び替えて、後の列はそのまま。２次元を超える配列場合、例えば、畳み込み演算で使う４次元配列の場合も同じ考え方で並び替え
    t = t[permutation] #正解ラベルは１次元なので、permutationで並び替えるだけ。

    return x, t

### reshape

# transpose

In [8]:
from my_common.util import init_sample_matrix

In [12]:
#入力画像の高さ、幅、および、チャネル数。画像の枚数
H  = 2
W  = 2 
C  = 2 
N  = 2 #入力画像の枚数
#xの用意
print("=== preparing of x===")
x1 = init_sample_matrix(filter_num = 0, channel=1, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)
x2 = init_sample_matrix(filter_num = 0, channel=2, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)
x3 = init_sample_matrix(filter_num = 0, channel=3, height=H, width=W) #filter番号(=画像番号)を識別する数値を与える(1,2~)

x = np.array([x1,x2,x3])
print(x.shape)
print(x)

print("x.transpose(2,1,0)")
print("https://deepage.net/features/numpy-transpose.htmlの解説にあるとおり、x(i,j,k)→x'(k,j,i)に変換する処理")
print("直感的には行１つ飛ばしで見つけた要素を、新しい行ベクトルにしている")
print(x.transpose(2,1,0))

=== preparing of x===
(3, 2, 2)
[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
x.transpose(2,1,0)
[[[111 211 311]
  [121 221 321]]

 [[112 212 312]
  [122 222 322]]]


# 参考URL
1. 乱数の生成
https://qiita.com/yubais/items/bf9ce0a8fefdcc0b0c97
    
2. パック/アンパック
https://docs.python.org/ja/3.7/tutorial/controlflow.html#unpacking-argument-lists

3. 配列のスライスについて
https://www.headboost.jp/python-numpy-array-how-to-handle/