# im2colとcol2imの理解

In [1]:
# coding: utf-8
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
import matplotlib.pyplot as plt
from common.util import *

In [2]:
#サンプル行列の初期化
def init_sample_matrix(row_size=6, col_size = 8):
    matrix = []

    for row in range(row_size):
        temp_row = []
        for col in range(col_size):
            elem = (row+1)*10 + col+1
            temp_row.append(elem)
        matrix.append(temp_row)

    return np.array(matrix)

In [3]:
m = init_sample_matrix()
print(m)

[[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]
 [41 42 43 44 45 46 47 48]
 [51 52 53 54 55 56 57 58]
 [61 62 63 64 65 66 67 68]]


init_sample_matrixは指定したサイズの行列を生成する。各要素の十の位が行番号を示し、一の位が列番号を示す。

In [ ]:
filter_size_x = 3
filter_size_y = 3
stride        = 1
pad           = 0

In [4]:
img = np.array([[m]])
print(img.shape)
col = im2col(img, filter_size_x, filter_size_y, stride, pad)
print(col)

(1, 1, 6, 8)
[[11. 12. 13. 21. 22. 23. 31. 32. 33.]
 [12. 13. 14. 22. 23. 24. 32. 33. 34.]
 [13. 14. 15. 23. 24. 25. 33. 34. 35.]
 [14. 15. 16. 24. 25. 26. 34. 35. 36.]
 [15. 16. 17. 25. 26. 27. 35. 36. 37.]
 [16. 17. 18. 26. 27. 28. 36. 37. 38.]
 [21. 22. 23. 31. 32. 33. 41. 42. 43.]
 [22. 23. 24. 32. 33. 34. 42. 43. 44.]
 [23. 24. 25. 33. 34. 35. 43. 44. 45.]
 [24. 25. 26. 34. 35. 36. 44. 45. 46.]
 [25. 26. 27. 35. 36. 37. 45. 46. 47.]
 [26. 27. 28. 36. 37. 38. 46. 47. 48.]
 [31. 32. 33. 41. 42. 43. 51. 52. 53.]
 [32. 33. 34. 42. 43. 44. 52. 53. 54.]
 [33. 34. 35. 43. 44. 45. 53. 54. 55.]
 [34. 35. 36. 44. 45. 46. 54. 55. 56.]
 [35. 36. 37. 45. 46. 47. 55. 56. 57.]
 [36. 37. 38. 46. 47. 48. 56. 57. 58.]
 [41. 42. 43. 51. 52. 53. 61. 62. 63.]
 [42. 43. 44. 52. 53. 54. 62. 63. 64.]
 [43. 44. 45. 53. 54. 55. 63. 64. 65.]
 [44. 45. 46. 54. 55. 56. 64. 65. 66.]
 [45. 46. 47. 55. 56. 57. 65. 66. 67.]
 [46. 47. 48. 56. 57. 58. 66. 67. 68.]]


参考URL1の説明に合ったように、フィルターの範囲の要素を並べて各行としていき、col展開する（参考URLの用語を流用)。
col2imも同様。ただし、こちらはimage表現に直した際に各ピクセルの値を加算していく所が特色的。

In [7]:
print(img.shape)

img_ret = col2im(col, img.shape, filter_size_x, filter_size_y, stride, pad)
print(img_ret.shape)
print(img_ret)

(1, 1, 6, 8)
(1, 1, 6, 8)
[[[[ 11.  24.  39.  42.  45.  48.  34.  18.]
   [ 42.  88. 138. 144. 150. 156. 108.  56.]
   [ 93. 192. 297. 306. 315. 324. 222. 114.]
   [123. 252. 387. 396. 405. 414. 282. 144.]
   [102. 208. 318. 324. 330. 336. 228. 116.]
   [ 61. 124. 189. 192. 195. 198. 134.  68.]]]]


# col展開でなぜ畳み込み演算が実現できるか、重みとフィルターの関係性は

# 参考URL
1. 基本的な理解(im2col/col2imの図解がわかりやすい)　https://qiita.com/t-tkd3a/items/6b17f296d61d14e12953
2. 行列積による畳込み(im2colした後の行列サイズやフィルターの解説についてわかりやすい) https://www.youtube.com/watch?v=PWPJVws7l0M